CREATE EXTENSION IF NOT EXISTS postgis;

--Clean database by dropping and creating schemes
DROP SCHEMA IF EXISTS nxt CASCADE;
DROP SCHEMA IF EXISTS damo_ruw CASCADE;
DROP SCHEMA IF EXISTS tmp CASCADE;
DROP SCHEMA IF EXISTS checks CASCADE;
DROP SCHEMA IF EXISTS hdb CASCADE;
DROP SCHEMA IF EXISTS fixed_data CASCADE;

CREATE SCHEMA IF NOT EXISTS nxt;
CREATE SCHEMA IF NOT EXISTS damo_ruw;
CREATE SCHEMA IF NOT EXISTS tmp;
CREATE SCHEMA IF NOT EXISTS checks;
CREATE SCHEMA IF NOT EXISTS hdb;
CREATE SCHEMA IF NOT EXISTS fixed_data;