version: '2'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgis/postgis
    restart: always
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: postgres

  # The hhnk docker is used for both the flask app (small webinterface to
  # have something to click in) and for the actual scripts.
  hhnk:
    build: .
    depends_on:
      - db
      - adminer
    ports:
      - 5000:5000
    # "command" is what is run if you do "docker-compose up". You can
    # still use this same docker for "docker-compose run hhnk python ...".
    command: python web/webinterface.py

    # Automatically pick up changes in the sql/ directory without needing to
    # re-build the entire docker. The "deploy" docker doesn't do this, so
    # there only the files present during docker generation are
    # available. When running the container on Windows, share this folder under
    # Docker -> Settings -> Resources -> File sharing
    volumes:
      - ./datachecker:/code/datachecker
      - ./modelbuilder:/code/modelbuilder
      - ./data:/code/data
      - ./tools:/code/tools
      - ./web:/code/web