#!/bin/bash
echo "Exporting data to FileGDB"
ogr2ogr -overwrite -sql "SELECT * FROM checks.afvoergebieden" -nln afvoergebieden -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt MULTIPOLYGON
ogr2ogr -overwrite -sql "SELECT code, geom,	omschrijving, startpeil, eindpeil, polderkant FROM checks.afvoerkunstwerken" -nln afvoerkunstwerken -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT * FROM checks.bridge" -nln bridge -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT id, organisation_id, created, code, type, bed_level, comment, name, talud_left, talud_right, image_url, geom, channel_type_id, bed_width, tabulated_width, tabulated_height, derived_bed_level, profile_valid, profile_type, typering, aanname, hasassumption FROM checks.channel" -nln channel -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Linestring
ogr2ogr -overwrite -sql "SELECT bufgeom, id, channel_type_id FROM checks.channel_linemerge" -nln channel_linemerge -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Polygon
ogr2ogr -overwrite -sql "SELECT id::int, geom, polder_id, lengte FROM checks.channel_loose" -nln channel_loose -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Polygon
ogr2ogr -overwrite -sql "SELECT id::int, geom, polder_id, lengte FROM checks.channel_nowayout" -nln channel_nowayout -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Polygon
ogr2ogr -overwrite -sql "SELECT * FROM checks.crossprofile" -nln crossprofile -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Polygon
ogr2ogr -overwrite -sql "SELECT * FROM checks.crosssection" -nln crosssection -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT id, organisation_id, created, code, type, bed_level_upstream , bed_level_downstream, width, length, allowed_flow_direction, height, material, shape as shape_culvert, description, image_url, geom, "'end'", start, num_timeseries, channel_code, channel_type_id, type_art, opmerking, wgtype_id, fixeddrainagelevelarea_id_1, fixeddrainagelevelarea_id_2, op_peilgrens, op_poldergrens, opmerk_datamining, aanname, isusable, hasassumption FROM checks.culvert" -nln culvert -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Linestring
ogr2ogr -overwrite -sql "SELECT tabel, code, opmerking, geom_point FROM checks.dubbele_kunstwerken" -nln dubbele_kunstwerk_point -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT tabel, code, opmerking, geom_line FROM checks.dubbele_kunstwerken" -nln dubbele_kunstwerk_line -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT * FROM checks.fixed_dam" -nln fixed_dam -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT * FROM checks.fixeddrainagelevelarea" -nln fixeddrainagelevelarea -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt MULTIPOLYGON
ogr2ogr -overwrite -sql "SELECT * FROM checks.geen_peil" -nln geen_peil -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Polygon
ogr2ogr -overwrite -sql "SELECT * FROM checks.invalid_geometry" -nln invalid_geometry -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Polygon
ogr2ogr -overwrite -sql "SELECT (ST_Dump(pointgeom)).geom as pointgeom, channel_id, levee_ring_id::int, channel_type_id FROM checks.kruising_zonder_kunstwerk" -nln kruising_zonder_kunstwerk -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT * FROM checks.overlappende_geometrie" -nln overlappende_geometrie -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Polygon
ogr2ogr -overwrite -sql "SELECT * FROM checks.polder" -nln polder -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt MULTIPOLYGON
ogr2ogr -overwrite -sql "SELECT * FROM checks.pumpstation" -nln pumpstation -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT * FROM checks.sluice" -nln sluice -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT id, organisation_id, created, code, type, crest_width, crest_level, name, lat_dis_coeff, angle, allowed_flow_direction, controlled, comment, discharge_coeff, image_url, geom, "'end'", start, num_timeseries, shape as weir_shape, controlled_ficeddrainagelevelarea_code, channel_code, type_function, opmerking, wgtype_id, channel_type_id, opmerk_datamining, aanname, isusable, hasassumption FROM checks.weirs" -nln weirs -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point
ogr2ogr -overwrite -sql "SELECT geom, levee_ring_id, levee_id, maximum_water_level, height, opmerking FROM checks.levee" -nln levee -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Linestring
ogr2ogr -overwrite -sql "SELECT * FROM checks.control_table" -nln control_table -f "FileGDB" ./output/datachecker_output.gdb PG:"host=p-project-db-d1.external-nens.local user=datachecker dbname=datachecker password=3JrYxhpO port=5432" -nlt Point