# -*- coding: utf-8 -*-

CULVERT_SNAPPED_TABLE_NAME = 'culvert_snapped'
CULVERT_OUTPUT_TABLE_NAME = 'tmp_sel_culvert'
CULVERT_BUFFER_SIZE = 0.2

START_POSITION = 0.0
END_POSITION = 1.0

SNAP_START_END_DISTANCE = 0.05
MINIMUM_LINE_LENGTH = SNAP_START_END_DISTANCE

