CREATE EXTENSION IF NOT EXISTS postgis;

DROP SCHEMA IF EXISTS checks CASCADE;
DROP SCHEMA IF EXISTS deelgebied CASCADE;
DROP SCHEMA IF EXISTS tmp CASCADE;
DROP SCHEMA IF EXISTS damo_ruw CASCADE;
DROP SCHEMA IF EXISTS hdb CASCADE;
DROP SCHEMA IF EXISTS feedback CASCADE;
DROP SCHEMA IF EXISTS nxt CASCADE;
DROP SCHEMA IF EXISTS fixed_data CASCADE;

CREATE SCHEMA checks;
CREATE SCHEMA deelgebied;
CREATE SCHEMA tmp;
CREATE SCHEMA damo_ruw;
CREATE SCHEMA hdb;
CREATE SCHEMA feedback;
CREATE SCHEMA nxt;
CREATE SCHEMA fixed_data;