name: docker creation

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:


# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can
      # access it
      - uses: actions/checkout@v2

      - name: Build docker
        run: docker-compose build

      - name: Publish the Docker image
        run: |
          docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          docker tag hhnk-modelbuilder_hhnk docker.pkg.github.com/nens/hhnk-modelbuilder/hhnk-modelbuilder
          docker push docker.pkg.github.com/nens/hhnk-modelbuilder/hhnk-modelbuilder
        if: github.ref == 'refs/heads/master'
        # Running this job only for master branch.
